### ISSUE TITLE
[SUGGESTION] Luckperms support

### ISSUE THREAD

**Issue by Weylend** [hypherionmc/MaintenanceMode#10]
What about adding permissions support?

**Comment by hypherionmc** [comment]
In what way would you like Luckperms supported? 

Like how would maintenance mode integrate into it?

**Comment by Weylend** [comment]
for accessing commands without op level

**Comment by hypherionmc** [comment]
That's fair, although the mod is designed to be OP only.

Would it only apply to specific commands, or to all the commands?

**Comment by Weylend** [comment]
I'm new to server administration and I don’t know what’s better
I have a small build server for my team that sometimes i turn off whitelist for guests so I only need permissions for:

/maintenance on/off
/maintenance addAllowed
/maintenance removeAllowed

it would be great for each command to have its own permission

**Comment by hypherionmc** [comment]
Alright will definitely see about adding support for it

**Comment by hypherionmc** [comment]
I am excited to share that LuckPerms support is finally coming with the upcoming 1.3.0 release

**Comment by hypherionmc** [comment]
Implemented with 1.3.0
