### ISSUE TITLE
Add an option to change the MOTD

### ISSUE THREAD

**Issue by guineuu** [hypherionmc/MaintenanceMode#2]
**Is your feature request related to a problem? Please describe.**
I'm using this mod in a modded server for my friends but we are from Spain so the message being in English and seemingly hardcoded bothers me.

**Describe the solution you'd like**
A new options key allowing to set the MOTD.

**Describe alternatives you've considered**
Harder to implenet whoud me some kind of localization (I could help with that) but I much prefer it being customizable.

**Additional context**
![-5881756613369510929_120](https://user-images.githubusercontent.com/51054489/175294933-c8c45a40-7c0a-48ca-b90c-7fd33df4818b.jpg)

**Comment by hypherionmc** [comment]
Hi there. A custom message can definitely be implemented. 

I agree that a localization system will be hard to do, and honestly not worth the effort when you could just have the users set their own message. I'll add it to the next update :)

**Comment by guineuu** [comment]
Thank you so much!

**Comment by hypherionmc** [comment]
You're welcome. I'm going to leave this open until it's implemented, otherwise I'm going to forget about it

**Comment by guineuu** [comment]
Oh yea sorry, that was a miss click

**Comment by hypherionmc** [comment]
Hey. Not sure what version of MC you use, but you test the Snapshot build. I added a new command `setMotd` to change that message.

https://ci.firstdarkdev.xyz/job/MaintenanceMode/

**Comment by guineuu** [comment]
works perfectly, thank you!
