### ISSUE TITLE
[BUG] Mod causes Watchdog error trying to set server icon

### ISSUE THREAD

**Issue by GoldenFurredFox** [hypherionmc/MaintenanceMode#5]
**Describe the bug**
When I have Maintenance Mode added to my server, the server encounters a Watchdog error once the first player has joined, and crashes trying to set the server icon.

**To Reproduce**
1. Launch Fabric 0.14.19 server on 1.18.2
2. Ensure whitelist is enabled
3. Whitelist yourself and op yourself
4. Join from the same machine using "localhost" in place of the IP
5. After mere moments of being in the world, the server will abruptly crash.

**Expected behavior**
The server lets you play normally and has no issues trying to set the server icon when maintenance mode isn't even enabled yet.

**Screenshots**
N/A

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
- Minecraft Version: 1.18.2
- Modloader
    - [ ] Forge
    - [X] Fabric
- Mod Loader Version: 0.14.19
- Mod Version: 1.1.1d for 1.18.X
- Java Version: 17

**Additional context**
I have Fullstack Watchdog version 1.0.1 installed to get a full stacktrace from the Watchdog report instead of just a single stacktrace.

**Crash Report**
[Here you go.](https://mclo.gs/U3TfhbU)

**Comment by hypherionmc** [comment]
Hi.

Thanks for reporting. This is definitely odd behavior as the mod should not try to modify the server icon if

1) Maintenance Mode is not enabled
2) There is no icon file matching the name specified in the config.

I'll try to replicate this on my side and let you know what I find
