### ISSUE TITLE
[INCOMPATIBILITY] MiniMOTD always takes control of display of server MOTD

### ISSUE THREAD

**Issue by NighthowlerStudios** [hypherionmc/MaintenanceMode#6]
This is a mirrored report of an incompatibility found on a Discord chat.

MiniMOTD has a lot of mixins surrounding minecraft's implementation of MOTD.  Due to this, Maintenance Mode is never able to send any packets for one as MiniMOTD keeps sending its own first, likely simply ignoring Maintenance Mode entirely.

It seems integration may need implemented to leverage MiniMOTD's implementation to display. If not, a workaround to force MiniMOTD to silence and let maintenance mode take temporary control.

~~https://www.curseforge.com/minecraft/mc-mods/maintenance-mode-forge-fabric-quilt~~
https://github.com/jpenilla/MiniMOTD/

**Comment by hypherionmc** [comment]
Why you link to my own mod. Thanks for adding this to github, otherwise I would've forgotten about it

**Comment by NighthowlerStudios** [comment]
lmao I don't know how that one happened.  you're welcome
