### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by notIkibo** [hypherionmc/MaintenanceMode#8]
**Describe the bug**
Backups aren't made after doing /maintenance backup. The command just dissappears without any feedback or any trace in console.

**To Reproduce**
1. Do /maintenance backup
2. wait
3. Nothing happens

**Expected behavior**
2. wait
3. See backup in mbackups folder

**Screenshots**

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
- Minecraft Version: 1.19.2
- Modloader
    - [ ] Forge
    - [x] Fabric
- Mod Loader Version: .19.21
- Mod Version:1.1.1
- Java Version:17

**Additional context**
I was the only one on the server. I don't know how it happened, but I have on backup (that is already too old).
But even dobackups on true and doing maintenance on doesn't do anything. I wanted to give it time, but there is no feedback for actually doing the backup.

**Crash Report**
If the game crashed, please include your latest crash report here

**Comment by notIkibo** [comment]
Do you need more Information?

**Comment by hypherionmc** [comment]
Hey, sorry I thought I replied to this.

Do you get any errors in your logs when trying to do the back? Or is it just completely doing nothing at all

**Comment by notIkibo** [comment]
I didn't look in the logs, but if it didn't show in the console, then it probably doesn't show in the logs

**Comment by hypherionmc** [comment]
True, but in some cases like with Pterodactyl panel, it doesn't show everything in the console. Some things only show up in the logs.

But if you're not using Pterodactyl, it's probably not the case. I'll do some testing on my side to confirm

**Comment by hypherionmc** [comment]
Just tested this on 1.19.2 fabric, and I can confirm the behavior of the command not replying anything, but after a bit the backup did generate.

![image](https://github.com/hypherionmc/MaintenanceMode/assets/63595580/3d9d530a-95c0-43ed-8360-601a3c004e66)

**Comment by notIkibo** [comment]
Like my backup files are half a gigabyte. So I should just type in the console maintenance backup and let it sit and wait?
I mostly already just let it do its thing (while still playing), but eventually the backup didn't happen. Does the backing up get disrupted by anything?

**Comment by hypherionmc** [comment]
Hmm that's interesting. I've definitely backed up servers of more than 1GB.

I think it's a good idea to let the command actually tell you it's starting the backup, and then maybe an in-game message to say when the backup is completed.


The only cases I've seen of the backup being disrupted, is when the server runs out of space, but you will see the error in your log. I will do some more testing with a bigger server and see what happens.

**Comment by hypherionmc** [comment]
This shouldn't be an issue in the 1.3.0 release anymore. It sends proper feedback now and logs all errors to the console.

If it still persists, feel free to re-open
