### ISSUE TITLE
[SUGGESTION] Scheduled Maintenance

### ISSUE THREAD

**Issue by BLACK4585** [hypherionmc/MaintenanceMode#9]
**Is your feature request related to a problem? Please describe.**
It would be very nice to schedule maintenances. At the moment, you have to tell every Player before that there will be a maintenance in a few hours or so.

**Describe the solution you'd like**
Something like `/maintenance schedule <time> [suffix]`, whereas <time> could be in minutes or a set time. E.g. when you enter `/maintenance schedule 30` it will schedule a maintenance for in 30 Minutes and when you enter `/maintenance schedule 5 <am/pm> it will create a schedule at a set time.

**Describe alternatives you've considered**
Notifying every player, which is very hard even if you don't have a global Discord Server.

**Additional context**
¯\_( ͡° ͜ʖ ͡°)_/¯

**Comment by hypherionmc** [comment]
Good extension of #3. Would require #4 to be implemented first.

(Sorry, just adding this as a note to myself here)

**Comment by hypherionmc** [comment]
Scheduled Maintenance (both starting and ending) is finally coming with upcoming release 1.3.0

**Comment by hypherionmc** [comment]
Implemented with release 1.3.0
